### ISSUE TITLE
Are you still using this?

### ISSUE THREAD

**Issue by cagnulein** [abobov/rss-generator#2]
Hi i would like to do a similar project, and so the question: are you still using it? Did you use some other tool to achieve the same result?
Thanks

**Comment by abobov** [comment]
Hi, I use it every day, feeds are created on a cron job.

I did it because I did not find the right tool or service.  I can't remember exactly what I was looking at, it turned out to be easier to do myself.

**Comment by cagnulein** [comment]
ok, i will try to add my forum as well.
Have a nice day!

**Comment by squromiv** [comment]
Hello. How to use it in Windows?

**Comment by cagnulein** [comment]
@squromiv did you try with Anaconda?

**Comment by squromiv** [comment]
@cagnulein 
Sorry, I am not a software developer. It took some time to learn. Finally, I installed Python 3.8, installed dependencies from "requirements.txt". I try to run "main.py" with url argument, but it fails. Could you show command line executing it?

**Comment by cagnulein** [comment]
which error do you see?
i'm not using this anymore so i can't help you

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 9 ott 2021 alle ore 18:42 squromiv ***@***.***>
ha scritto:

**Comment by abobov** [comment]
@squromiv Please fill a new issue with error text what you see.

Also, you can not use this for generating RSS for any site, you first need to create a parser for that site. Describe what site are you trying to add in new issue may be I can help you with that.
