### ISSUE TITLE
createaforum.com plugin

### ISSUE THREAD

**Issue by squromiv** [abobov/rss-generator#3]
Hello. I need to get RSS-feed for [this](https://turkishshows.createaforum.com/31/urban-legends/165/) topic. So I installed dependencies from "requirements.txt" and ran "main.py" app with url as argument.
![1](https://user-images.githubusercontent.com/15985877/137370734-d1435613-35c8-417a-ac1e-1fce3bf5b3ee.png)
Am I doing something wrong?

**Comment by abobov** [comment]
Please try run from [branch](https://github.com/abobov/rss-generator/tree/fix/3-createaforum-plugin) with different URL:
```sh
main.py https://turkishshows.createaforum.com/31/urban-legends/
```

**Comment by squromiv** [comment]
Thanks a lot! It looks good now in terminal. And how to add such a feed to rss-readers?

**Comment by abobov** [comment]
You could save feed into a file `main.py http://example.com > example.xml` and open that XML in your RSS reader.  If you are using online readers then before you need to serve that file into the web where the reader can reach that file.

Also, it's common to create some periodic jobs to update that file with new messages.

**Comment by squromiv** [comment]
@abobov 
I tried to get the feed for [this topic](https://turkishshows.createaforum.com/6/'let's-get-to-know-each-other'/) and got the [error](http://s01.geekpic.net/di-R3H4X7.jpeg)
Sorry, I am newbie to python and it is not clear for me.

**Comment by abobov** [comment]
Please try to run this command before script:
```batch
chcp 65001
set PYTHONIOENCODING=utf-8
```

**Comment by squromiv** [comment]
Great support! It works. Let`s close the issue.
